### ISSUE TITLE
Code execution continues after exception

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-oidcng#4]
I had an issue with my remote IDP metadata, leading to the following errors being logged by OIDCNG:

> May 25 13:05:28 sv1811044.frd.tshsdir.local OIDC: [http-nio-9195-exec-1] org.springframework.security.saml.provider.AbstractHostedProviderService Invalid signature for remote provider metadata https://engine.example.org/authentication/idp/metadata. Unable to trust.

I noticed that, despite the exception being raised, requests are still fired against EngineBlock, even with the exception message from OIDCng appended to the HTTP request!

Engineblock log:
May 25 12:29:10 sv1811043 EBLOG[1643]: [2020-05-25 12:29:10] app.NOTICE: [404]Unroutable URI: '**/authentication/idp/metadata. Unable to trust.**' {"session_id":null,"request_id":"5ecb9df5e8f27"} []

EB Apache log:
May 25 12:29:10 sv1811043 HTTPD-EB: 10.19.84.248 - - [25/May/2020:12:29:09 +0200] "GET **/authentication/idp/metadata.%20Unable%20to%20trust**. HTTP/1.1" 404 2567 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by oharsta** [comment]
We have migrated from spring-security-saml to spring-security core. See https://spring.io/blog/2020/09/22/spring-security-saml-extensions-1-x-eol-on-october-6-2021 for the reason why. The new oidcng codebase also does not longer use the EB metadata, but instead certificate, sso-location and entity-id are picked up from the configuration. This also resolves this issue. We will be releasing version 4.0.0 shortly.
